[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'Yggdroot/indentLine'

# 非同期処理全般
[[plugins]]
repo = 'Shougo/vimproc.vim'

[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'roxma/nvim-yarp'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'tyru/open-browser.vim'
on_source = ['tyru/open-browser-github.vim']

[[plugins]]
repo = 'tyru/open-browser-github.vim'

[[plugins]]
repo    = 'vim-airline/vim-airline'
depends = ['/vim-airline-themes']
depends = ['tpope/vim-fugitive']

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'tpope/vim-fugitive'
